### ISSUE TITLE
Consider building instrumentation-java with Gradle.

### ISSUE THREAD

**Issue by sebright** [google/instrumentation-java#108]
It would be nice to only have to maintain one build file, instead of separate build files for Bazel and Maven.  We would need to ensure that we can still build with Java 6, upload releases to Maven Central, build Protocol Buffers, and run static analysis and style checks with Gradle.

**Comment by adriancole** [comment]
ideally this build could work on osx and only require bazel (assuming
that's the chosen one). Ex bootstrapping with a vendored and pinned version
of protoc as I noticed recently this is a bit of a pain.

**Comment by bogdandrutu** [comment]
I think we decided to go only with maven. We will update the travis to run tests on OSX as well. Thanks adriancole@.

**Comment by sebright** [comment]
Reopening, since we are trying out Gradle.

We should also update the instructions on building the project in CONTRIBUTING.md.

**Comment by sebright** [comment]
Added in #158.
