### ISSUE TITLE
are TagKey and TagValue idiomatic?

### ISSUE THREAD

**Issue by adriancole** [google/instrumentation-java#11]
I can see the desire to solve the problem of length constraints with types, but in java, you can't extend String. Making TagKey and TagValue wrapper types makes it clunky to specify tags, in a way that will be even more obvious when other JVM languages use this. TagKey and TagValue feel clunkier than the Tag object itself.

Is there some other reason besides length we are doing this? If not, I'd highly recommend reverting and moving the length constraint to a precondition. Libraries should be a joy to use.

**Comment by sebright** [comment]
As I understand it, applications should use a limited number of unique keys and values, for performance reasons.  The keys and values will probably be written as constants that can be reused, and the classes will let us only validate strings once.  The validation code also checks that the strings are printable ASCII characters.  How will the classes affect other JVM languages?

`Tag` isn't used much, so I think we can remove it.

**Comment by adriancole** [comment]
There's nothing about performance that makes a string wrapper a better
constant or better for reuse than a string. It is just making the api
more difficult to use. Validation of ascii is also not a good enough
reason, as this can be done without requiring those declaring
constants to use special types.

If I'm using clojure, I'd want to not think about arbitrarily
different types when thinking of key/values.

ex. (hello :name "John" :salutation "Hi")

I'd also prefer this in Java. the more unnecessary types we define,
the more bloated and burdensome the code is to use.

**Comment by adriancole** [comment]
For a tangible next step, even if wrappers are used internally (which
so far, I really don't see a need for), I'd recommend not leaking
these into the public api, or at least not requiring them.

I can punt a pull request on this to show what I mean.. if it doesn't
make the thing more idiomatic or less crufty, I'd be happy to have
given it a shot.

**Comment by dinooliva** [comment]
Our experience has been that, if we don't sanitize tag keys and values when they are created then we have to sanitize them at every use, which is not only tedious but also error prone (I can't begin to tell you how many problems this has caused in the past).

I don't see another solution in Java of how to guarantee that the strings are properly sanitzed. As Kristen has mentioned, most client code should define their tag keys and values statically and just refer to them as constants, which has worked out pretty well in practice.
