### ISSUE TITLE
Document tags as printable ascii

### ISSUE THREAD

**Issue by adriancole** [google/instrumentation-java#12]
Tags seems check length, presumably as a byte-length guard as opposed to a character length one. If they are the same, we're probably talking printable ascii. If that's the case, we should document somewhere that names and values must be printable ascii (else they will be replaced with '?' or such). Maybe on the Tag type or something that accepts it. If there are other rules, such as downcasing or case insensitive keys, we should document that in the same place as we document the constraints of character set and length.

**Comment by dinooliva** [comment]
We've added javadoc documentation on the restrictions on the inputs to the factory methods for TagKey and TagValue - I believe that should address this issue.
