### ISSUE TITLE
Remove Guava and jsr305 dependencies from the API artifact

### ISSUE THREAD

**Issue by zhangkun83** [google/instrumentation-java#13]
They are only lightly used and can be easily swapped out. A dependency-free library is more appealing to users. In particular, users are concerned about Guava dependency because they may also be using Guava, and the two Guava versions may conflict.

**Comment by dinooliva** [comment]
Hi Kun - while we can remove these external dependencies in this case, in general we will need to depend on external libraries for our implementation work - how do the issues of external dependencies (e.g Guava) generally get resolved?

**Comment by zhangkun83** [comment]
The dependencies of your implementation don't matter. Only the API artifact's dependency is of concern here, because gRPC only depends on the Census API.

**Comment by dinooliva** [comment]
Removing the dependency on Guava is not a problem. Removing the dependency on jsr305 means removing our uses of @Nullable, which are useful to specify in our APIs for both documentation purposes and for static-analysis/verification available in many IDE's (e.g. eclipse).

How do you deal with this in gRPC?

**Comment by zhangkun83** [comment]
In grpc-context we concluded that not having `@Nullable` is an acceptable trade-off for a dependency-free library, which prospective users of grpc-context such as Zipkin care about more. From gRPC's perspective, I think it's fine for census-core to depend on jsr305 because gRPC-core already has such dependency.

**Comment by sebright** [comment]
See #15 and #18.

**Comment by sebright** [comment]
Reopening because #15 didn't handle jsr305.

**Comment by adriancole** [comment]
Not sure about eclipse, but many tools read internal Nullable annotations.
For example, Google auto-value.

Concretely speaking, how important are the few cases null can exist in this
library worth adding a dep?

Those using this library are certainly using a library that doesn't depend
on jsr305. Most libraries do not depend on 305 else this wouldn't be a
discussion. This library was intentionally split from grpc for others to
use, right? So, should we rely on transitive deps to make decisions here?

**Comment by dinooliva** [comment]
For now, we don't believe dependency on jsr305 is a big issue so we are going to keep it for now. If it turns out to be problematic, we'll revisit the issue.
