### ISSUE TITLE
Rename API artifact to census-api

### ISSUE THREAD

**Issue by zhangkun83** [google/instrumentation-java#14]
census-core doesn't indicate the fact that it's pure API. Because grpc-core depends on the API artifact, people may mistake census-core as an implementation and raise concern over grpc-core's dependency on it.

**Comment by dinooliva** [comment]
I'll look into it when we make the next release - if there are any problems/concerns, I'll let you know.

**Comment by dinooliva** [comment]
This was done in the last release.
