### ISSUE TITLE
Define a gRPC Context key for StatsContext

### ISSUE THREAD

**Issue by zhangkun83** [google/instrumentation-java#142]
Something similar to [GrpcTraceUtils](https://github.com/google/instrumentation-java/blob/master/core_context_impl/src/main/java/com/google/instrumentation/trace/GrpcTraceUtils.java). This is needed for communicating StatsContext between the application and the gRPC core.

The [StatsRunner](https://github.com/google/instrumentation-java/blob/master/examples/src/main/java/com/google/instrumentation/stats/StatsRunner.java) example should be using this instead of defining its own key.

**Comment by bogdandrutu** [comment]
SGTM. Kristine let's do this after our meeting tomorrow about having the grpc.Context in the API versus what trace has currently.

**Comment by songy23** [comment]
Fixed in PR https://github.com/google/instrumentation-java/pull/299.
