### ISSUE TITLE
Build and run tests in 'core' directory with Maven.

### ISSUE THREAD

**Issue by sebright** [google/instrumentation-java#147]
We currently disable the tests in `core/pom.xml` because they create a circular dependency between the `core` and `core_impl` directories (https://github.com/google/instrumentation-java/blob/1435c7fdf4be28ef724350558be6984f39d386c8/core/pom.xml#L36).  `core_impl` depends on `core`, and the `core` tests have a runtime dependency on the non-test code under `core_impl`.  One solution is to move the tests to `core_impl/`.

**Comment by sebright** [comment]
We moved to Gradle, which can handle this directory structure, but I think that we should still try to simplify the dependencies between directories.

**Comment by bogdandrutu** [comment]
Won't fix. Moved to gradle.

**Comment by sebright** [comment]
I opened a new issue for the test directory structure: #168
