### ISSUE TITLE
Replace "Census" with "Instrumentation" throughout the repository.

### ISSUE THREAD

**Issue by sebright** [google/instrumentation-java#150]
We still use "Census" in a few places, such as the readme and `pom.xml` files.  The `pom.xml` change is necessary for #149.

**Comment by sebright** [comment]
I removed most occurrence in #164.  We just need to update the Maven group and artifact IDs and Protocol Buffers.

**Comment by bogdandrutu** [comment]
I think with the latest gradle configs we are good on the maven group.

**Comment by sebright** [comment]
We also no longer depend on Census.proto.
