### ISSUE TITLE
Should we allow the Travis CHECK_GIT_HISTORY build job to fail the build?

### ISSUE THREAD

**Issue by sebright** [google/instrumentation-java#225]
The git history check is currently listed under `allow_failures`, so it can't fail the build.  I put it there initially because I wanted to make sure that there weren't too many false positives.  I was wondering if we should remove it from `allow_failures` now that we have been using it for a few weeks.  It fails when a pull request contains merge commits.

**Comment by bogdandrutu** [comment]
Should this be closed?

**Comment by sebright** [comment]
I made a PR (#239), but it hasn't been merged yet.
