### ISSUE TITLE
CensusGrpcContext API semantics

### ISSUE THREAD

**Issue by zhangkun83** [google/instrumentation-java#26]
`getInstace()` will return `null` if the implementation is not found. It should be annotated with `@Nullable`.

`get()`'s javadoc says

> If there is no associated CensusContext, the default CensusContext is returned.

However, because only CensusContextFactory can get the default CensusContext, CensusGrpcContext has no access to the currently used CensusContextFactory implementation. Returning `null` is very unfriendly to users. Maybe change it to:

```
get(Context context, CensusContextFactory censusFactory)
```

**Comment by zhangkun83** [comment]
Never mind. This CensusGrpcContext as a pluggable API would make a tedious user experience, because the application would need to inject the implementations for both CensusContextFactory and CensusGrpcContext. Had a talk with @ejona86. We think we can get away with a concrete helper class that interacts with gRPC Context, without any need to have alternative implementations for the helper.

**Comment by dinooliva** [comment]
We have removed this API since it wasn't useful. We will continue to look into integrating with the gRPC context.
