### ISSUE TITLE
CensusContext.serialize should accept a destination buffer

### ISSUE THREAD

**Issue by carl-mastrangelo** [google/instrumentation-java#33]
Current, CensusContext.serialize always returns a buffer, which creates excess garbage.  A better interface would be to accept an existing buffer to write into.  This would allow callers to recycle buffers.  Also, it would allow the context to serialize into an existing buffer of other data, avoiding a copy.

**Comment by dinooliva** [comment]
It probably doesn't make sense to use ByteBuffer for a destination - I think either java.io.OutputStream (or java.io.ObjectOutputStream to be more compatible with the Serializable interface) makes more sense.

Thoughts?

**Comment by dinooliva** [comment]
The other question is, if we go with OutputStream, should serialize throw and IOException in case writing to the the stream fails?

**Comment by dinooliva** [comment]
We've changed serialize/deserialize to take an OutputStream/InputStream and to throw IOException in the case of an error writing/reading the stream.

**Comment by dinooliva** [comment]
I am going to close this issue for now - feel free to reopen it with any comments or questions.
