### ISSUE TITLE
CensusContextFactory.deserialize should clarify mutabilty

### ISSUE THREAD

**Issue by carl-mastrangelo** [google/instrumentation-java#34]
CensusContextFactory.deserialize doesn't say whether it will mutate the passed in ByteBuffer.   This means that all callers will have to make a defensive copy to avoid accidentally having the underlying data, mark, position, or limit values changed.

It should be clear from the documentation that it will be treated as immutable.

**Comment by dinooliva** [comment]
That makes sense - is there a standard notation/annotation to indicate that or should I add a note in the documentation?

**Comment by dinooliva** [comment]
We've changed the interface to take a InputStream, so I believe this is a non-issue now. Feel free to reopen with any questions/comments.
