### ISSUE TITLE
Inconsistent time units in RpcConstants

### ISSUE THREAD

**Issue by zhangkun83** [google/instrumentation-java#88]
`RPC_CLIENT_SERVER_ELAPSED_TIME`, `RPC_SERVER_SERVER_ELAPSED_TIME` and `RPC_SERVER_SERVER_LATENCY` are documented to be in `msec`, which is milliseconds.

`RPC_CLIENT_ROUNDTRIP_LATENCY` is documented to be `RPC roundtrip latency us`, which is microseconds. There is no reason for it to be different.

**Comment by sebright** [comment]
There is also an inconsistency in units between the `MeasurementDescriptor` and `ViewDescriptors` for client roundtrip latency:

https://github.com/google/instrumentation-java/blob/7f0ce697c792f6c539c6cfcbd85e253040cb7454/core/java/com/google/instrumentation/stats/RpcConstants.java#L58-L62

https://github.com/google/instrumentation-java/blob/7f0ce697c792f6c539c6cfcbd85e253040cb7454/core/java/com/google/instrumentation/stats/RpcConstants.java#L139-L145

**Comment by sebright** [comment]
This was fixed by #130.
